executable = run_train.sh
arguments = $(classifier) $(f) $(param)
output = train_outputs/outputfile_$(param)_c$(classifier)_f$(f).$(CLUSTER).txt
error = train_outputs/errorfile_$(param)_c$(classifier)_f$(f).$(CLUSTER).txt
log = train_outputs/example.job_$(param)_c$(classifier)_f$(f).$(CLUSTER).txt
request_gpus = 1
+MaxRuntime = 23.5*60*60
queue classifier,f,param from (
1,5,c1c2
1,3,c1c2
1,1,c1c2
)