# Data setup (step 1)
data_dir: /vols/cms/us322/nsbi_for_dihiggs/data
morphing_setup: /vols/cms/us322/nsbi_for_dihiggs/data/setup.h5

# MG generation (step 2)
madgraph:
    dir: /vols/cms/us322/nsbi_for_dihiggs/madgraph-stable/MG5_aMC_v3_5_1 # Stable v3.5.1
    test_run: True
    output_dir: /vols/cms/us322/02_event_generation_14/mg_processes
    energy: 14 # 100 TeV (FC) or 14 TeV (HL-LHC)

# Delphes (step 3)
delphes:
    input_dir_prefix: /vols/cms/us322/02b_final_events_14
    output_file: /vols/cms/us322/03_post_delphes_data_14/delphes
    long_term_storage_dir: /vols/cms/us322/03_post_delphes_data_14
    
# Sampling (step 4)
sampling:
    input_dir: /vols/cms/us322/03_post_delphes_data_14
    output_dir: /vols/cms/us322/04_new_dataset_dihiggs_14
    
# Plotting
plotting:
    fancy_name:
        c0: $c_{\phi}$
        c1: $c_{\phi d}$
        c2: $c_{t \phi}$
    color:
        c0: red
        c1: blue
        c2: green