# Data setup (step 1)
data_dir: /home/hep/us322/SBI/nsbi_for_dihiggs/data
morphing_setup: /home/hep/us322/SBI/nsbi_for_dihiggs/data/setup.h5

# MG generation (step 2)
madgraph:
    dir: /home/hep/us322/mg5amcnlo/
    n_runs: 2
    output_dir: /home/hep/us322/SBI/nsbi_for_dihiggs/mg_processes
    energy: 100

# Delphes (step 3)
delphes:
    input_dir_prefix: /home/hep/us322/SBI/nsbi_for_dihiggs/mg_processes/
    output_file: /vols/cms/us322/post_delphes_data/delphes
    long_term_storage_dir: /vols/cms/us322/post_delphes_data
    
# Sampling (step 4)
sampling:
    input_dir: /vols/cms/us322/post_delphes_data/
    output_dir: /home/hep/us322/SBI/nsbi_for_dihiggs/samples/
    
# Plotting
plotting:
    fancy_name:
        c0: $c_{\phi}$
        c1: $c_{\phi d}$
        c2: $c_{t \phi}$
    color:
        c0: red
        c1: blue
        c2: green