# Data setup (step 1)
data_dir: /vols/cms/us322/nsbi_for_dihiggs/data
morphing_setup: /vols/cms/us322/nsbi_for_dihiggs/data/setup.h5

# MG generation (step 2)
madgraph:
    #dir: /vols/cms/us322/nsbi_for_dihiggs/mg5amcnlo # v3.5.1
    dir: /vols/cms/us322/test_sbi/mg5amcnlo # Latest version.
    n_runs: 1
    output_dir: /vols/cms/us322/nsbi_for_dihiggs/mg_processes
    energy: 14 # 100 TeV (FC) or 14 TeV (HL-LHC)

# Delphes (step 3)
delphes:
    input_dir_prefix: /vols/cms/us322/nsbi_for_dihiggs/events
    output_file: /vols/cms/us322/post_delphes_data/delphes
    long_term_storage_dir: /vols/cms/us322/post_delphes_data
    
# Sampling (step 4)
sampling:
    input_dir: /vols/cms/us322/post_delphes_data
    #input_dir: /vols/cms/us322/nsbi_for_dihiggs # Use author's dataset
    output_dir: /vols/cms/us322/new_dataset_dihiggs
    
# Plotting
plotting:
    fancy_name:
        c0: $c_{\phi}$
        c1: $c_{\phi d}$
        c2: $c_{t \phi}$
    color:
        c0: red
        c1: blue
        c2: green