C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     1
C     
      SUBROUTINE MP_SSS6_0(S1, S2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP
      COMPLEX*32 S1(*)
      COMPLEX*32 S2(*)
      COMPLEX*32 S3(*)
      COMPLEX*32 VERTEX
      VERTEX = COUP*(-CI * S3(5)*S2(5)*S1(5))
      END


