C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2)*P(2,1) - (13*P(1,3)*P(2,1))/62. - (13*P(1,4)*P(2,1))/62.
C      - (13*P(1,2)*P(2,3))/62. + (P(1,3)*P(2,3))/62. +
C      (P(1,4)*P(2,3))/62. - (13*P(1,2)*P(2,4))/62. +
C      (P(1,3)*P(2,4))/62. + (P(1,4)*P(2,4))/62. -
C      (20*P(-1,1)*P(-1,2)*Metric(1,2))/31. +
C      (19*P(-1,2)**2*Metric(1,2))/62. +
C      (2*P(-1,1)*P(-1,3)*Metric(1,2))/31. +
C      (23*P(-1,2)*P(-1,3)*Metric(1,2))/62. -
C      (13*P(-1,3)**2*Metric(1,2))/62. +
C      (2*P(-1,1)*P(-1,4)*Metric(1,2))/31. +
C      (23*P(-1,2)*P(-1,4)*Metric(1,2))/62. -
C      (13*P(-1,3)*P(-1,4)*Metric(1,2))/31. -
C      (13*P(-1,4)**2*Metric(1,2))/62.
C     
      SUBROUTINE MP_VVSS20_0(V1, V2, S3, S4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP
      COMPLEX*32 P1(0:3)
      COMPLEX*32 P2(0:3)
      COMPLEX*32 P3(0:3)
      COMPLEX*32 P4(0:3)
      COMPLEX*32 S3(*)
      COMPLEX*32 S4(*)
      COMPLEX*32 TMP10
      COMPLEX*32 TMP12
      COMPLEX*32 TMP13
      COMPLEX*32 TMP14
      COMPLEX*32 TMP15
      COMPLEX*32 TMP16
      COMPLEX*32 TMP17
      COMPLEX*32 TMP18
      COMPLEX*32 TMP19
      COMPLEX*32 TMP2
      COMPLEX*32 TMP20
      COMPLEX*32 TMP21
      COMPLEX*32 TMP4
      COMPLEX*32 TMP5
      COMPLEX*32 TMP6
      COMPLEX*32 TMP8
      COMPLEX*32 V1(*)
      COMPLEX*32 V2(*)
      COMPLEX*32 VERTEX
      P1(0) = V1(1)
      P1(1) = V1(2)
      P1(2) = V1(3)
      P1(3) = V1(4)
      P2(0) = V2(1)
      P2(1) = V2(2)
      P2(2) = V2(3)
      P2(3) = V2(4)
      P3(0) = S3(1)
      P3(1) = S3(2)
      P3(2) = S3(3)
      P3(3) = S3(4)
      P4(0) = S4(1)
      P4(1) = S4(2)
      P4(2) = S4(3)
      P4(3) = S4(4)
      TMP10 = (P3(0)*V1(5)-P3(1)*V1(6)-P3(2)*V1(7)-P3(3)*V1(8))
      TMP12 = (P1(0)*P3(0)-P1(1)*P3(1)-P1(2)*P3(2)-P1(3)*P3(3))
      TMP13 = (P2(0)*P3(0)-P2(1)*P3(1)-P2(2)*P3(2)-P2(3)*P3(3))
      TMP14 = (V1(5)*P4(0)-V1(6)*P4(1)-V1(7)*P4(2)-V1(8)*P4(3))
      TMP15 = (V2(5)*P4(0)-V2(6)*P4(1)-V2(7)*P4(2)-V2(8)*P4(3))
      TMP16 = (P2(0)*P2(0)-P2(1)*P2(1)-P2(2)*P2(2)-P2(3)*P2(3))
      TMP17 = (P3(0)*P3(0)-P3(1)*P3(1)-P3(2)*P3(2)-P3(3)*P3(3))
      TMP18 = (P1(0)*P4(0)-P1(1)*P4(1)-P1(2)*P4(2)-P1(3)*P4(3))
      TMP19 = (P2(0)*P4(0)-P2(1)*P4(1)-P2(2)*P4(2)-P2(3)*P4(3))
      TMP2 = (P2(0)*P1(0)-P2(1)*P1(1)-P2(2)*P1(2)-P2(3)*P1(3))
      TMP20 = (P3(0)*P4(0)-P3(1)*P4(1)-P3(2)*P4(2)-P3(3)*P4(3))
      TMP21 = (P4(0)*P4(0)-P4(1)*P4(1)-P4(2)*P4(2)-P4(3)*P4(3))
      TMP4 = (P2(0)*V1(5)-P2(1)*V1(6)-P2(2)*V1(7)-P2(3)*V1(8))
      TMP5 = (P1(0)*V2(5)-P1(1)*V2(6)-P1(2)*V2(7)-P1(3)*V2(8))
      TMP6 = (V2(5)*V1(5)-V2(6)*V1(6)-V2(7)*V1(7)-V2(8)*V1(8))
      TMP8 = (V2(5)*P3(0)-V2(6)*P3(1)-V2(7)*P3(2)-V2(8)*P3(3))
      VERTEX = COUP*(-13Q0/62Q0 * S3(5)*S4(5)*(TMP6*4Q0/13Q0*(-10Q0 *
     $  CI*(TMP2)+19Q0/4Q0 * CI*(TMP16)+CI*(TMP12+TMP18)+23Q0/4Q0 * CI
     $ *(TMP13+TMP19)-13Q0/4Q0 * CI*(TMP17+TMP21)-13Q0/2Q0 * CI*(TMP20)
     $ )+(TMP10*1Q0/13Q0*(-13Q0/1Q0 * CI*(TMP5)+CI*(TMP8+TMP15))
     $ +(TMP14*1Q0/13Q0*(-13Q0/1Q0 * CI*(TMP5)+CI*(TMP8+TMP15))-TMP4*(
     $ -62Q0/13Q0 * CI*(TMP5)+CI*(TMP8+TMP15))))))
      END


