C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     1
C     
      SUBROUTINE SSS6_0(S1, S2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 S1(*)
      COMPLEX*16 S2(*)
      COMPLEX*16 S3(*)
      COMPLEX*16 VERTEX
      VERTEX = COUP*(-CI * S3(5)*S2(5)*S1(5))
      END


