C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2)*P(2,1) - (9*P(1,3)*P(2,1))/26. - (9*P(1,4)*P(2,1))/26. -
C      (9*P(1,2)*P(2,3))/26. - (9*P(1,2)*P(2,4))/26. -
C      (17*P(-1,1)*P(-1,2)*Metric(1,2))/26. +
C      (9*P(-1,2)**2*Metric(1,2))/26. +
C      (3*P(-1,1)*P(-1,3)*Metric(1,2))/26. +
C      (6*P(-1,2)*P(-1,3)*Metric(1,2))/13. -
C      (3*P(-1,3)**2*Metric(1,2))/13. +
C      (3*P(-1,1)*P(-1,4)*Metric(1,2))/26. +
C      (6*P(-1,2)*P(-1,4)*Metric(1,2))/13. -
C      (6*P(-1,3)*P(-1,4)*Metric(1,2))/13. -
C      (3*P(-1,4)**2*Metric(1,2))/13.
C     
      SUBROUTINE VVSS19_0(V1, V2, S3, S4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 P1(0:3)
      COMPLEX*16 P2(0:3)
      COMPLEX*16 P3(0:3)
      COMPLEX*16 P4(0:3)
      COMPLEX*16 S3(*)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP10
      COMPLEX*16 TMP12
      COMPLEX*16 TMP13
      COMPLEX*16 TMP14
      COMPLEX*16 TMP15
      COMPLEX*16 TMP16
      COMPLEX*16 TMP17
      COMPLEX*16 TMP18
      COMPLEX*16 TMP19
      COMPLEX*16 TMP2
      COMPLEX*16 TMP20
      COMPLEX*16 TMP21
      COMPLEX*16 TMP4
      COMPLEX*16 TMP5
      COMPLEX*16 TMP6
      COMPLEX*16 TMP8
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 VERTEX
      P1(0) = V1(1)
      P1(1) = V1(2)
      P1(2) = V1(3)
      P1(3) = V1(4)
      P2(0) = V2(1)
      P2(1) = V2(2)
      P2(2) = V2(3)
      P2(3) = V2(4)
      P3(0) = S3(1)
      P3(1) = S3(2)
      P3(2) = S3(3)
      P3(3) = S3(4)
      P4(0) = S4(1)
      P4(1) = S4(2)
      P4(2) = S4(3)
      P4(3) = S4(4)
      TMP10 = (P3(0)*V1(5)-P3(1)*V1(6)-P3(2)*V1(7)-P3(3)*V1(8))
      TMP12 = (P1(0)*P3(0)-P1(1)*P3(1)-P1(2)*P3(2)-P1(3)*P3(3))
      TMP13 = (P2(0)*P3(0)-P2(1)*P3(1)-P2(2)*P3(2)-P2(3)*P3(3))
      TMP14 = (V1(5)*P4(0)-V1(6)*P4(1)-V1(7)*P4(2)-V1(8)*P4(3))
      TMP15 = (V2(5)*P4(0)-V2(6)*P4(1)-V2(7)*P4(2)-V2(8)*P4(3))
      TMP16 = (P2(0)*P2(0)-P2(1)*P2(1)-P2(2)*P2(2)-P2(3)*P2(3))
      TMP17 = (P3(0)*P3(0)-P3(1)*P3(1)-P3(2)*P3(2)-P3(3)*P3(3))
      TMP18 = (P1(0)*P4(0)-P1(1)*P4(1)-P1(2)*P4(2)-P1(3)*P4(3))
      TMP19 = (P2(0)*P4(0)-P2(1)*P4(1)-P2(2)*P4(2)-P2(3)*P4(3))
      TMP2 = (P2(0)*P1(0)-P2(1)*P1(1)-P2(2)*P1(2)-P2(3)*P1(3))
      TMP20 = (P3(0)*P4(0)-P3(1)*P4(1)-P3(2)*P4(2)-P3(3)*P4(3))
      TMP21 = (P4(0)*P4(0)-P4(1)*P4(1)-P4(2)*P4(2)-P4(3)*P4(3))
      TMP4 = (P2(0)*V1(5)-P2(1)*V1(6)-P2(2)*V1(7)-P2(3)*V1(8))
      TMP5 = (P1(0)*V2(5)-P1(1)*V2(6)-P1(2)*V2(7)-P1(3)*V2(8))
      TMP6 = (V2(5)*V1(5)-V2(6)*V1(6)-V2(7)*V1(7)-V2(8)*V1(8))
      TMP8 = (V2(5)*P3(0)-V2(6)*P3(1)-V2(7)*P3(2)-V2(8)*P3(3))
      VERTEX = COUP*9D0/26D0 * S3(5)*S4(5)*(TMP6*(-4D0/3D0)*(-17D0
     $ /12D0 * CI*(TMP2)+3D0/4D0 * CI*(TMP16)+1D0/4D0 * CI*(TMP12
     $ +TMP18)+CI*(TMP13+TMP19)-1D0/2D0 * CI*(TMP17+TMP21)-CI*(TMP20))
     $ +(TMP4*(-26D0/9D0 * CI*(TMP5)+CI*(TMP8+TMP15))+TMP5*(+CI*(TMP10
     $ +TMP14))))
      END


