ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTatNLO-LO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_153 = ', GC_153
      WRITE(*,2) 'GC_156 = ', GC_156
      WRITE(*,2) 'GC_161 = ', GC_161
      WRITE(*,2) 'R2GC_569_1756 = ', R2GC_569_1756
      WRITE(*,2) 'R2GC_595_1779 = ', R2GC_595_1779
      WRITE(*,2) 'UVGC_1753_108_1eps = ', UVGC_1753_108_1EPS
      WRITE(*,2) 'UVGC_1794_165_1eps = ', UVGC_1794_165_1EPS
      WRITE(*,2) 'UVGC_1861_253_1eps = ', UVGC_1861_253_1EPS
      WRITE(*,2) 'GC_357 = ', GC_357
      WRITE(*,2) 'GC_358 = ', GC_358
      WRITE(*,2) 'GC_360 = ', GC_360
      WRITE(*,2) 'R2GC_1297_467 = ', R2GC_1297_467
      WRITE(*,2) 'R2GC_1298_468 = ', R2GC_1298_468
      WRITE(*,2) 'R2GC_570_1757 = ', R2GC_570_1757
      WRITE(*,2) 'R2GC_618_1801 = ', R2GC_618_1801
      WRITE(*,2) 'R2GC_629_1812 = ', R2GC_629_1812
      WRITE(*,2) 'R2GC_630_1813 = ', R2GC_630_1813
      WRITE(*,2) 'R2GC_631_1814 = ', R2GC_631_1814
      WRITE(*,2) 'UVGC_1755_110_1eps = ', UVGC_1755_110_1EPS
      WRITE(*,2) 'UVGC_1833_208_1eps = ', UVGC_1833_208_1EPS
      WRITE(*,2) 'UVGC_1918_351_1eps = ', UVGC_1918_351_1EPS
      WRITE(*,2) 'UVGC_1753_108 = ', UVGC_1753_108
      WRITE(*,2) 'UVGC_1794_165 = ', UVGC_1794_165
      WRITE(*,2) 'UVGC_1861_253 = ', UVGC_1861_253
      WRITE(*,2) 'UVGC_1861_254 = ', UVGC_1861_254
      WRITE(*,2) 'UVGC_1755_110 = ', UVGC_1755_110
      WRITE(*,2) 'UVGC_1918_351 = ', UVGC_1918_351
      WRITE(*,2) 'UVGC_1918_352 = ', UVGC_1918_352
      WRITE(*,2) 'UVGC_1833_208 = ', UVGC_1833_208
      WRITE(*,2) 'GC_1822 = ', GC_1822
      WRITE(*,2) 'GC_1842 = ', GC_1842
      WRITE(*,2) 'GC_322 = ', GC_322
      WRITE(*,2) 'GC_336 = ', GC_336
      WRITE(*,2) 'GC_420 = ', GC_420
      WRITE(*,2) 'GC_422 = ', GC_422
      WRITE(*,2) 'GC_431 = ', GC_431
      WRITE(*,2) 'GC_546 = ', GC_546
      WRITE(*,2) 'GC_65 = ', GC_65
