      SUBROUTINE DLUM_5(LUM)
C     ****************************************************            
C         
C     Generated by MadGraph5_aMC@NLO v. 3.5.1, 2023-07-11
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     RETURNS PARTON LUMINOSITIES FOR MADFKS                          
C        
C     
C     Process: g u > h h u NP<=2 QCD<=100 QED<=99 [ all = QCD ] NP^2=4
C      QCD^2<=6 QED^2<=4
C     Process: g c > h h c NP<=2 QCD<=100 QED<=99 [ all = QCD ] NP^2=4
C      QCD^2<=6 QED^2<=4
C     Process: g d > h h d NP<=2 QCD<=100 QED<=99 [ all = QCD ] NP^2=4
C      QCD^2<=6 QED^2<=4
C     Process: g s > h h s NP<=2 QCD<=100 QED<=99 [ all = QCD ] NP^2=4
C      QCD^2<=6 QED^2<=4
C     Process: g b > h h b NP<=2 QCD<=100 QED<=99 [ all = QCD ] NP^2=4
C      QCD^2<=6 QED^2<=4
C     
C     ****************************************************            
C         
      IMPLICIT NONE
C     
C     CONSTANTS                                                       
C         
C     
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      DOUBLE PRECISION       CONV
      PARAMETER (CONV=389379660D0)  !CONV TO PICOBARNS             
C     
C     ARGUMENTS                                                       
C         
C     
      DOUBLE PRECISION LUM
C     
C     LOCAL VARIABLES                                                 
C         
C     
      INTEGER I, ICROSS,LP
      DOUBLE PRECISION G1
      DOUBLE PRECISION D2,U2,S2,C2,B2
C     
C     EXTERNAL FUNCTIONS                                              
C         
C     
      DOUBLE PRECISION PDG2PDF
C     
C     GLOBAL VARIABLES                                                
C         
C     
      INTEGER              IPROC
      DOUBLE PRECISION PD(0:MAXPROC)
      COMMON /SUBPROC/ PD, IPROC
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
      INTEGER IMIRROR
      COMMON/CMIRROR/IMIRROR
C     
C     STUFF FOR DRESSED EE COLLISIONS
C     
      INCLUDE 'eepdf.inc'
      DOUBLE PRECISION EE_COMP_PROD
      DOUBLE PRECISION DUMMY_COMPONENTS(N_EE)
      DOUBLE PRECISION G1_COMPONENTS(N_EE)
      DOUBLE PRECISION D2_COMPONENTS(N_EE),U2_COMPONENTS(N_EE)
     $ ,S2_COMPONENTS(N_EE),C2_COMPONENTS(N_EE),B2_COMPONENTS(N_EE)

      INTEGER I_EE
      INCLUDE '../../Source/PDF/pdf.inc'
C     
C     DATA                                                            
C         
C     
      DATA G1/1*1D0/
      DATA D2,U2,S2,C2,B2/5*1D0/
      DATA ICROSS/1/
C     ----------                                                      
C         
C     BEGIN CODE                                                      
C         
C     ----------                                                      
C         
      LUM = 0D0
      IF (ABS(LPP(1)) .GE. 1) THEN
        G1=PDG2PDF(LPP(1),0,1,XBK(1),DSQRT(Q2FACT(1)))
        IF ((ABS(LPP(1)).EQ.4.OR.ABS(LPP(1)).EQ.3)
     $   .AND.PDLABEL.NE.'none') G1_COMPONENTS(1:N_EE) =
     $    EE_COMPONENTS(1:N_EE)
      ENDIF
      IF (ABS(LPP(2)) .GE. 1) THEN
        D2=PDG2PDF(LPP(2),1,2,XBK(2),DSQRT(Q2FACT(2)))
        IF ((ABS(LPP(2)).EQ.4.OR.ABS(LPP(2)).EQ.3)
     $   .AND.PDLABEL.NE.'none') D2_COMPONENTS(1:N_EE) =
     $    EE_COMPONENTS(1:N_EE)
        U2=PDG2PDF(LPP(2),2,2,XBK(2),DSQRT(Q2FACT(2)))
        IF ((ABS(LPP(2)).EQ.4.OR.ABS(LPP(2)).EQ.3)
     $   .AND.PDLABEL.NE.'none') U2_COMPONENTS(1:N_EE) =
     $    EE_COMPONENTS(1:N_EE)
        S2=PDG2PDF(LPP(2),3,2,XBK(2),DSQRT(Q2FACT(2)))
        IF ((ABS(LPP(2)).EQ.4.OR.ABS(LPP(2)).EQ.3)
     $   .AND.PDLABEL.NE.'none') S2_COMPONENTS(1:N_EE) =
     $    EE_COMPONENTS(1:N_EE)
        C2=PDG2PDF(LPP(2),4,2,XBK(2),DSQRT(Q2FACT(2)))
        IF ((ABS(LPP(2)).EQ.4.OR.ABS(LPP(2)).EQ.3)
     $   .AND.PDLABEL.NE.'none') C2_COMPONENTS(1:N_EE) =
     $    EE_COMPONENTS(1:N_EE)
        B2=PDG2PDF(LPP(2),5,2,XBK(2),DSQRT(Q2FACT(2)))
        IF ((ABS(LPP(2)).EQ.4.OR.ABS(LPP(2)).EQ.3)
     $   .AND.PDLABEL.NE.'none') B2_COMPONENTS(1:N_EE) =
     $    EE_COMPONENTS(1:N_EE)
      ENDIF
      PD(0) = 0D0
      IPROC = 0
      IPROC=IPROC+1  ! g u > h h u
      PD(IPROC) = G1*U2
      IF (ABS(LPP(1)).EQ.ABS(LPP(2)).AND. (ABS(LPP(1))
     $ .EQ.3.OR.ABS(LPP(1)).EQ.4).AND.PDLABEL.NE.'none')PD(IPROC)
     $ =EE_COMP_PROD(G1_COMPONENTS,U2_COMPONENTS)
      IPROC=IPROC+1  ! g c > h h c
      PD(IPROC) = G1*C2
      IF (ABS(LPP(1)).EQ.ABS(LPP(2)).AND. (ABS(LPP(1))
     $ .EQ.3.OR.ABS(LPP(1)).EQ.4).AND.PDLABEL.NE.'none')PD(IPROC)
     $ =EE_COMP_PROD(G1_COMPONENTS,C2_COMPONENTS)
      IPROC=IPROC+1  ! g d > h h d
      PD(IPROC) = G1*D2
      IF (ABS(LPP(1)).EQ.ABS(LPP(2)).AND. (ABS(LPP(1))
     $ .EQ.3.OR.ABS(LPP(1)).EQ.4).AND.PDLABEL.NE.'none')PD(IPROC)
     $ =EE_COMP_PROD(G1_COMPONENTS,D2_COMPONENTS)
      IPROC=IPROC+1  ! g s > h h s
      PD(IPROC) = G1*S2
      IF (ABS(LPP(1)).EQ.ABS(LPP(2)).AND. (ABS(LPP(1))
     $ .EQ.3.OR.ABS(LPP(1)).EQ.4).AND.PDLABEL.NE.'none')PD(IPROC)
     $ =EE_COMP_PROD(G1_COMPONENTS,S2_COMPONENTS)
      IPROC=IPROC+1  ! g b > h h b
      PD(IPROC) = G1*B2
      IF (ABS(LPP(1)).EQ.ABS(LPP(2)).AND. (ABS(LPP(1))
     $ .EQ.3.OR.ABS(LPP(1)).EQ.4).AND.PDLABEL.NE.'none')PD(IPROC)
     $ =EE_COMP_PROD(G1_COMPONENTS,B2_COMPONENTS)
      DO I=1,IPROC
        IF (NINCOMING.EQ.2) THEN
          LUM = LUM + PD(I) * CONV
        ELSE
          LUM = LUM + PD(I)
        ENDIF
      ENDDO
      RETURN
      END

