C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(-1,1)*P(-1,2) + P(-1,1)*P(-1,3) + P(-1,2)*P(-1,3)
C     
      SUBROUTINE SSS10_1(S2, S3, COUP, M1, W1,S1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 M1
      COMPLEX*16 P1(0:3)
      COMPLEX*16 P2(0:3)
      COMPLEX*16 P3(0:3)
      COMPLEX*16 S1(5)
      COMPLEX*16 S2(*)
      COMPLEX*16 S3(*)
      COMPLEX*16 TMP12
      COMPLEX*16 TMP13
      COMPLEX*16 TMP2
      REAL*8 W1
      COMPLEX*16 DENOM
      P2(0) = S2(1)
      P2(1) = S2(2)
      P2(2) = S2(3)
      P2(3) = S2(4)
      P3(0) = S3(1)
      P3(1) = S3(2)
      P3(2) = S3(3)
      P3(3) = S3(4)
      S1(1) = +S2(1)+S3(1)
      S1(2) = +S2(2)+S3(2)
      S1(3) = +S2(3)+S3(3)
      S1(4) = +S2(4)+S3(4)
      P1(0) = -S1(1)
      P1(1) = -S1(2)
      P1(2) = -S1(3)
      P1(3) = -S1(4)
      TMP12 = (P1(0)*P3(0)-P1(1)*P3(1)-P1(2)*P3(2)-P1(3)*P3(3))
      TMP13 = (P2(0)*P3(0)-P2(1)*P3(1)-P2(2)*P3(2)-P2(3)*P3(3))
      TMP2 = (P2(0)*P1(0)-P2(1)*P1(1)-P2(2)*P1(2)-P2(3)*P1(3))
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI
     $ * W1))
      S1(5)= DENOM*S2(5)*S3(5)*(+CI*(TMP2+TMP12+TMP13))
      END


