C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (P(1,2)*P(2,1) - P(-1,1)*P(-1,2)*Metric(1,2)) + Coup(2) * (P(1,2)*P(2,1) - (P(-1,1)*P(-1,2)*Metric(1,2))/2. + (P(-1,2)**2*Metric(1,2))/2. + (P(-1,2)*P(-1,3)*Metric(1,2))/2.)
C     
      SUBROUTINE VVS12_13L2P0_1(P2, S3, COUP1, COUP2, M1, W1, P1,
     $  COEFF)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      REAL*8 M1
      COMPLEX*16 P1(0:3)
      COMPLEX*16 COUP2
      COMPLEX*16 TMP13
      REAL*8 W1
      COMPLEX*16 COUP1
      INCLUDE 'coef_specs.inc'
      COMPLEX*16 COEFF(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)
      COMPLEX*16 TMP2
      COMPLEX*16 S3(*)
      COMPLEX*16 TMP16
      COMPLEX*16 P2(0:3)
      COMPLEX*16 P3(0:3)
      P3(0) = S3(1)
      P3(1) = S3(2)
      P3(2) = S3(3)
      P3(3) = S3(4)
      P1(0) = +P2(0)+S3(1)
      P1(1) = +P2(1)+S3(2)
      P1(2) = +P2(2)+S3(3)
      P1(3) = +P2(3)+S3(4)
      TMP2 = (P2(0)*P1(0)-P2(1)*P1(1)-P2(2)*P1(2)-P2(3)*P1(3))
      TMP13 = (P2(0)*P3(0)-P2(1)*P3(1)-P2(2)*P3(2)-P2(3)*P3(3))
      TMP16 = (P2(0)*P2(0)-P2(1)*P2(1)-P2(2)*P2(2)-P2(3)*P2(3))
      COEFF(1,0,1)= -S3(5)*(COUP2*1D0/2D0*(-2D0 * CI*(P2(0)*P1(0))+CI
     $ *(TMP2+TMP16+TMP13))+COUP1*(-CI*(P2(0)*P1(0))+CI*(TMP2)))
      COEFF(2,0,1)= P1(0)*P2(1)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,0,1)= P1(0)*P2(2)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,0,1)= P1(0)*P2(3)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,1,1)= -1D0/2D0 * COUP2*S3(5)*(+CI*(P2(0)+P3(0))-CI*(P1(0)
     $ ))
      COEFF(2,1,1)= P2(1)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,1,1)= P2(2)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,1,1)= P2(3)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,2,1)= S3(5)*(COUP2*1D0/2D0*(+3D0 * CI*(P2(1))+CI*(P1(1)
     $ +P3(1)))+COUP1*(+CI*(P2(1)+P1(1))))
      COEFF(2,2,1)= P1(0)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,2,1)= 0D0
      COEFF(4,2,1)= 0D0
      COEFF(1,3,1)= S3(5)*(COUP2*1D0/2D0*(+3D0 * CI*(P2(2))+CI*(P1(2)
     $ +P3(2)))+COUP1*(+CI*(P2(2)+P1(2))))
      COEFF(2,3,1)= 0D0
      COEFF(3,3,1)= P1(0)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,3,1)= 0D0
      COEFF(1,4,1)= S3(5)*(COUP2*1D0/2D0*(+3D0 * CI*(P2(3))+CI*(P1(3)
     $ +P3(3)))+COUP1*(+CI*(P2(3)+P1(3))))
      COEFF(2,4,1)= 0D0
      COEFF(3,4,1)= 0D0
      COEFF(4,4,1)= P1(0)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,5,1)= 0D0
      COEFF(2,5,1)= 0D0
      COEFF(3,5,1)= 0D0
      COEFF(4,5,1)= 0D0
      COEFF(1,6,1)= 0D0
      COEFF(2,6,1)= S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,6,1)= 0D0
      COEFF(4,6,1)= 0D0
      COEFF(1,7,1)= S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,7,1)= 0D0
      COEFF(3,7,1)= 0D0
      COEFF(4,7,1)= 0D0
      COEFF(1,8,1)= 0D0
      COEFF(2,8,1)= 0D0
      COEFF(3,8,1)= S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,8,1)= 0D0
      COEFF(1,9,1)= 0D0
      COEFF(2,9,1)= 0D0
      COEFF(3,9,1)= 0D0
      COEFF(4,9,1)= 0D0
      COEFF(1,10,1)= S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,10,1)= 0D0
      COEFF(3,10,1)= 0D0
      COEFF(4,10,1)= 0D0
      COEFF(1,11,1)= 0D0
      COEFF(2,11,1)= 0D0
      COEFF(3,11,1)= 0D0
      COEFF(4,11,1)= S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,12,1)= 0D0
      COEFF(2,12,1)= 0D0
      COEFF(3,12,1)= 0D0
      COEFF(4,12,1)= 0D0
      COEFF(1,13,1)= 0D0
      COEFF(2,13,1)= 0D0
      COEFF(3,13,1)= 0D0
      COEFF(4,13,1)= 0D0
      COEFF(1,14,1)= S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,14,1)= 0D0
      COEFF(3,14,1)= 0D0
      COEFF(4,14,1)= 0D0
      COEFF(1,0,2)= -P1(1)*P2(0)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,0,2)= -S3(5)*(COUP2*1D0/2D0*(+2D0 * CI*(P2(1)*P1(1))+CI
     $ *(TMP2+TMP16+TMP13))+COUP1*(+CI*(P2(1)*P1(1)+TMP2)))
      COEFF(3,0,2)= -P1(1)*P2(2)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,0,2)= -P1(1)*P2(3)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,1,2)= -P1(1)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,1,2)= -S3(5)*(COUP2*1D0/2D0*(+3D0 * CI*(P2(0))+CI*(P1(0)
     $ +P3(0)))+COUP1*(+CI*(P2(0)+P1(0))))
      COEFF(3,1,2)= 0D0
      COEFF(4,1,2)= 0D0
      COEFF(1,2,2)= -P2(0)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,2,2)= 1D0/2D0 * COUP2*S3(5)*(+CI*(P2(1)+P3(1))-CI*(P1(1))
     $ )
      COEFF(3,2,2)= -P2(2)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,2,2)= -P2(3)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,3,2)= 0D0
      COEFF(2,3,2)= S3(5)*(COUP2*1D0/2D0*(+3D0 * CI*(P2(2))+CI*(P1(2)
     $ +P3(2)))+COUP1*(+CI*(P2(2)+P1(2))))
      COEFF(3,3,2)= -P1(1)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,3,2)= 0D0
      COEFF(1,4,2)= 0D0
      COEFF(2,4,2)= S3(5)*(COUP2*1D0/2D0*(+3D0 * CI*(P2(3))+CI*(P1(3)
     $ +P3(3)))+COUP1*(+CI*(P2(3)+P1(3))))
      COEFF(3,4,2)= 0D0
      COEFF(4,4,2)= -P1(1)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,5,2)= 0D0
      COEFF(2,5,2)= -S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,5,2)= 0D0
      COEFF(4,5,2)= 0D0
      COEFF(1,6,2)= -S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,6,2)= 0D0
      COEFF(3,6,2)= 0D0
      COEFF(4,6,2)= 0D0
      COEFF(1,7,2)= 0D0
      COEFF(2,7,2)= 0D0
      COEFF(3,7,2)= 0D0
      COEFF(4,7,2)= 0D0
      COEFF(1,8,2)= 0D0
      COEFF(2,8,2)= 0D0
      COEFF(3,8,2)= 0D0
      COEFF(4,8,2)= 0D0
      COEFF(1,9,2)= 0D0
      COEFF(2,9,2)= 0D0
      COEFF(3,9,2)= -S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,9,2)= 0D0
      COEFF(1,10,2)= 0D0
      COEFF(2,10,2)= S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,10,2)= 0D0
      COEFF(4,10,2)= 0D0
      COEFF(1,11,2)= 0D0
      COEFF(2,11,2)= 0D0
      COEFF(3,11,2)= 0D0
      COEFF(4,11,2)= 0D0
      COEFF(1,12,2)= 0D0
      COEFF(2,12,2)= 0D0
      COEFF(3,12,2)= 0D0
      COEFF(4,12,2)= -S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,13,2)= 0D0
      COEFF(2,13,2)= 0D0
      COEFF(3,13,2)= 0D0
      COEFF(4,13,2)= 0D0
      COEFF(1,14,2)= 0D0
      COEFF(2,14,2)= S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,14,2)= 0D0
      COEFF(4,14,2)= 0D0
      COEFF(1,0,3)= -P1(2)*P2(0)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,0,3)= -P1(2)*P2(1)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,0,3)= -S3(5)*(COUP2*1D0/2D0*(+2D0 * CI*(P2(2)*P1(2))+CI
     $ *(TMP2+TMP16+TMP13))+COUP1*(+CI*(P2(2)*P1(2)+TMP2)))
      COEFF(4,0,3)= -P1(2)*P2(3)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,1,3)= -P1(2)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,1,3)= 0D0
      COEFF(3,1,3)= -S3(5)*(COUP2*1D0/2D0*(+3D0 * CI*(P2(0))+CI*(P1(0)
     $ +P3(0)))+COUP1*(+CI*(P2(0)+P1(0))))
      COEFF(4,1,3)= 0D0
      COEFF(1,2,3)= 0D0
      COEFF(2,2,3)= -P1(2)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,2,3)= S3(5)*(COUP2*1D0/2D0*(+3D0 * CI*(P2(1))+CI*(P1(1)
     $ +P3(1)))+COUP1*(+CI*(P2(1)+P1(1))))
      COEFF(4,2,3)= 0D0
      COEFF(1,3,3)= -P2(0)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,3,3)= -P2(1)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,3,3)= 1D0/2D0 * COUP2*S3(5)*(+CI*(P2(2)+P3(2))-CI*(P1(2))
     $ )
      COEFF(4,3,3)= -P2(3)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,4,3)= 0D0
      COEFF(2,4,3)= 0D0
      COEFF(3,4,3)= S3(5)*(COUP2*1D0/2D0*(+3D0 * CI*(P2(3))+CI*(P1(3)
     $ +P3(3)))+COUP1*(+CI*(P2(3)+P1(3))))
      COEFF(4,4,3)= -P1(2)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,5,3)= 0D0
      COEFF(2,5,3)= 0D0
      COEFF(3,5,3)= -S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,5,3)= 0D0
      COEFF(1,6,3)= 0D0
      COEFF(2,6,3)= 0D0
      COEFF(3,6,3)= 0D0
      COEFF(4,6,3)= 0D0
      COEFF(1,7,3)= 0D0
      COEFF(2,7,3)= 0D0
      COEFF(3,7,3)= S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,7,3)= 0D0
      COEFF(1,8,3)= -S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,8,3)= 0D0
      COEFF(3,8,3)= 0D0
      COEFF(4,8,3)= 0D0
      COEFF(1,9,3)= 0D0
      COEFF(2,9,3)= -S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,9,3)= 0D0
      COEFF(4,9,3)= 0D0
      COEFF(1,10,3)= 0D0
      COEFF(2,10,3)= 0D0
      COEFF(3,10,3)= 0D0
      COEFF(4,10,3)= 0D0
      COEFF(1,11,3)= 0D0
      COEFF(2,11,3)= 0D0
      COEFF(3,11,3)= 0D0
      COEFF(4,11,3)= 0D0
      COEFF(1,12,3)= 0D0
      COEFF(2,12,3)= 0D0
      COEFF(3,12,3)= 0D0
      COEFF(4,12,3)= 0D0
      COEFF(1,13,3)= 0D0
      COEFF(2,13,3)= 0D0
      COEFF(3,13,3)= 0D0
      COEFF(4,13,3)= -S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,14,3)= 0D0
      COEFF(2,14,3)= 0D0
      COEFF(3,14,3)= S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,14,3)= 0D0
      COEFF(1,0,4)= -P1(3)*P2(0)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,0,4)= -P1(3)*P2(1)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,0,4)= -P1(3)*P2(2)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,0,4)= -S3(5)*(COUP2*1D0/2D0*(+2D0 * CI*(P2(3)*P1(3))+CI
     $ *(TMP2+TMP16+TMP13))+COUP1*(+CI*(P2(3)*P1(3)+TMP2)))
      COEFF(1,1,4)= -P1(3)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,1,4)= 0D0
      COEFF(3,1,4)= 0D0
      COEFF(4,1,4)= -S3(5)*(COUP2*1D0/2D0*(+3D0 * CI*(P2(0))+CI*(P1(0)
     $ +P3(0)))+COUP1*(+CI*(P2(0)+P1(0))))
      COEFF(1,2,4)= 0D0
      COEFF(2,2,4)= -P1(3)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,2,4)= 0D0
      COEFF(4,2,4)= S3(5)*(COUP2*1D0/2D0*(+3D0 * CI*(P2(1))+CI*(P1(1)
     $ +P3(1)))+COUP1*(+CI*(P2(1)+P1(1))))
      COEFF(1,3,4)= 0D0
      COEFF(2,3,4)= 0D0
      COEFF(3,3,4)= -P1(3)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,3,4)= S3(5)*(COUP2*1D0/2D0*(+3D0 * CI*(P2(2))+CI*(P1(2)
     $ +P3(2)))+COUP1*(+CI*(P2(2)+P1(2))))
      COEFF(1,4,4)= -P2(0)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,4,4)= -P2(1)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,4,4)= -P2(2)*S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,4,4)= 1D0/2D0 * COUP2*S3(5)*(+CI*(P2(3)+P3(3))-CI*(P1(3))
     $ )
      COEFF(1,5,4)= 0D0
      COEFF(2,5,4)= 0D0
      COEFF(3,5,4)= 0D0
      COEFF(4,5,4)= -S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,6,4)= 0D0
      COEFF(2,6,4)= 0D0
      COEFF(3,6,4)= 0D0
      COEFF(4,6,4)= 0D0
      COEFF(1,7,4)= 0D0
      COEFF(2,7,4)= 0D0
      COEFF(3,7,4)= 0D0
      COEFF(4,7,4)= S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,8,4)= 0D0
      COEFF(2,8,4)= 0D0
      COEFF(3,8,4)= 0D0
      COEFF(4,8,4)= 0D0
      COEFF(1,9,4)= 0D0
      COEFF(2,9,4)= 0D0
      COEFF(3,9,4)= 0D0
      COEFF(4,9,4)= 0D0
      COEFF(1,10,4)= 0D0
      COEFF(2,10,4)= 0D0
      COEFF(3,10,4)= 0D0
      COEFF(4,10,4)= S3(5)*(+CI*(COUP1+COUP2))
      COEFF(1,11,4)= -S3(5)*(+CI*(COUP1+COUP2))
      COEFF(2,11,4)= 0D0
      COEFF(3,11,4)= 0D0
      COEFF(4,11,4)= 0D0
      COEFF(1,12,4)= 0D0
      COEFF(2,12,4)= -S3(5)*(+CI*(COUP1+COUP2))
      COEFF(3,12,4)= 0D0
      COEFF(4,12,4)= 0D0
      COEFF(1,13,4)= 0D0
      COEFF(2,13,4)= 0D0
      COEFF(3,13,4)= -S3(5)*(+CI*(COUP1+COUP2))
      COEFF(4,13,4)= 0D0
      COEFF(1,14,4)= 0D0
      COEFF(2,14,4)= 0D0
      COEFF(3,14,4)= 0D0
      COEFF(4,14,4)= 0D0
      END


