C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (P(1,2)*P(2,1) - P(-1,1)*P(-1,2)*Metric(1,2)) + Coup(2) * (P(1,2)*P(2,1) - (P(-1,1)*P(-1,2)*Metric(1,2))/2. + (P(-1,2)**2*Metric(1,2))/2. + (P(-1,2)*P(-1,3)*Metric(1,2))/2. + (P(-1,2)*P(-1,4)*Metric(1,2))/2.)
C     
      SUBROUTINE VVSS15_18P0_1(V2, S3, S4, COUP1, COUP2, M1, W1,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      REAL*8 M1
      COMPLEX*16 P1(0:3)
      COMPLEX*16 P2(0:3)
      COMPLEX*16 P3(0:3)
      COMPLEX*16 P4(0:3)
      COMPLEX*16 S3(*)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP13
      COMPLEX*16 TMP16
      COMPLEX*16 TMP19
      COMPLEX*16 TMP2
      COMPLEX*16 TMP5
      COMPLEX*16 V1(8)
      COMPLEX*16 V2(*)
      REAL*8 W1
      COMPLEX*16 DENOM
      P2(0) = V2(1)
      P2(1) = V2(2)
      P2(2) = V2(3)
      P2(3) = V2(4)
      P3(0) = S3(1)
      P3(1) = S3(2)
      P3(2) = S3(3)
      P3(3) = S3(4)
      P4(0) = S4(1)
      P4(1) = S4(2)
      P4(2) = S4(3)
      P4(3) = S4(4)
      V1(1) = +V2(1)+S3(1)+S4(1)
      V1(2) = +V2(2)+S3(2)+S4(2)
      V1(3) = +V2(3)+S3(3)+S4(3)
      V1(4) = +V2(4)+S3(4)+S4(4)
      P1(0) = -V1(1)
      P1(1) = -V1(2)
      P1(2) = -V1(3)
      P1(3) = -V1(4)
      TMP13 = (P2(0)*P3(0)-P2(1)*P3(1)-P2(2)*P3(2)-P2(3)*P3(3))
      TMP16 = (P2(0)*P2(0)-P2(1)*P2(1)-P2(2)*P2(2)-P2(3)*P2(3))
      TMP19 = (P2(0)*P4(0)-P2(1)*P4(1)-P2(2)*P4(2)-P2(3)*P4(3))
      TMP2 = (P2(0)*P1(0)-P2(1)*P1(1)-P2(2)*P1(2)-P2(3)*P1(3))
      TMP5 = (P1(0)*V2(5)-P1(1)*V2(6)-P1(2)*V2(7)-P1(3)*V2(8))
      DENOM = 1D0/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI*
     $  W1))
      V1(5)= DENOM*(-1D0/2D0 )* S3(5)*S4(5)*(V2(5)*(COUP2*(-CI*(TMP2)
     $ +CI*(TMP16+TMP13+TMP19))-2D0 * CI*(TMP2*COUP1))+2D0*(P2(0)*TMP5
     $ *(+CI*(COUP1+COUP2))))
      V1(6)= DENOM*(-1D0/2D0 )* S3(5)*S4(5)*(V2(6)*(COUP2*(-CI*(TMP2)
     $ +CI*(TMP16+TMP13+TMP19))-2D0 * CI*(TMP2*COUP1))+2D0*(P2(1)*TMP5
     $ *(+CI*(COUP1+COUP2))))
      V1(7)= DENOM*(-1D0/2D0 )* S3(5)*S4(5)*(V2(7)*(COUP2*(-CI*(TMP2)
     $ +CI*(TMP16+TMP13+TMP19))-2D0 * CI*(TMP2*COUP1))+2D0*(P2(2)*TMP5
     $ *(+CI*(COUP1+COUP2))))
      V1(8)= DENOM*(-1D0/2D0 )* S3(5)*S4(5)*(V2(8)*(COUP2*(-CI*(TMP2)
     $ +CI*(TMP16+TMP13+TMP19))-2D0 * CI*(TMP2*COUP1))+2D0*(P2(3)*TMP5
     $ *(+CI*(COUP1+COUP2))))
      END


